version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=approval-service
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=password"]
      interval: 10s
      timeout: 20s
      retries: 5
    restart: on-failure

volumes:
  mysql-data:
